### ISSUE TITLE
Invalid schema error

### ISSUE THREAD

**Issue by findingorder** [CodingGarden/trello-clone#10]
Tried running server per instructions in README, and I got this error:
(node:7697) UnhandledPromiseRejectionWarning: Error: Invalid schema, expected `mongodb` or `mongodb+srv`
The error also throws when I run test.
Any suggestions on how I can make this work?
Thanks,
Phil

**Comment by SnellOKC** [comment]
I'm getting the same error. Here are my full error logs:

```
EDMA006485-MBP:server matthew.snell$ npm start

> trello-clone-server@0.0.0 start /Users/matthew.snell/Projects/trello-clone/server
> node src/

(node:80809) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
info: Feathers application started on http://localhost:3030
error: Unhandled Rejection at: Promise  Promise {
  <rejected> **Error: Invalid schema, expected `mongodb` or `mongodb+srv`
    at module.exports** (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/url_parser.js:21:21)
    at deprecated (internal/util.js:53:15)
    at connect (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/operations/mongo_client_ops.js:195:3)
    at connectOp (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)
    at executeOperation (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/utils.js:416:24)
    at MongoClient.connect (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/mongo_client.js:175:10)
    at Promise (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongoose/lib/connection.js:612:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongoose/lib/connection.js:609:19)
    at Mongoose.connect (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongoose/lib/index.js:321:15)
    at Function.module.exports (/Users/matthew.snell/Projects/trello-clone/server/src/mongoose.js:4:12)
    at Function.configure (/Users/matthew.snell/Projects/trello-clone/server/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Object.<anonymous> (/Users/matthew.snell/Projects/trello-clone/server/src/app.js:42:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32) } Error: Invalid schema, expected `mongodb` or `mongodb+srv`
    at module.exports (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/url_parser.js:21:21)
    at deprecated (internal/util.js:53:15)
    at connect (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/operations/mongo_client_ops.js:195:3)
    at connectOp (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)
    at executeOperation (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/utils.js:416:24)
    at MongoClient.connect (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongodb/lib/mongo_client.js:175:10)
    at Promise (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongoose/lib/connection.js:612:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongoose/lib/connection.js:609:19)
    at Mongoose.connect (/Users/matthew.snell/Projects/trello-clone/server/node_modules/mongoose/lib/index.js:321:15)
    at Function.module.exports (/Users/matthew.snell/Projects/trello-clone/server/src/mongoose.js:4:12)
    at Function.configure (/Users/matthew.snell/Projects/trello-clone/server/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Object.<anonymous> (/Users/matthew.snell/Projects/trello-clone/server/src/app.js:42:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
```

**Comment by SnellOKC** [comment]
@findingorder Solved. In your `default.json` you need to either 

a) change the `"mongodb": "MONGO_DB_URI"` to be `"mongodb": "mongodb://localhost:27017/"`, or
b) create a `.env` file in the server folder and store `MONGO_DB_URI = "mongodb://localhost:27017/"` as an environment variable.

**Comment by w3cj** [comment]
Fixed with setup instructions in server README.
